# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\CMake\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\CMake\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Gosh_\Desktop\Programming\Projects\C++\Raylib\BulletFun

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Gosh_\Desktop\Programming\Projects\C++\Raylib\BulletFun

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"C:\Program Files\CMake\bin\cmake-gui.exe" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\CMake\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Gosh_\Desktop\Programming\Projects\C++\Raylib\BulletFun\CMakeFiles C:\Users\Gosh_\Desktop\Programming\Projects\C++\Raylib\BulletFun\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Gosh_\Desktop\Programming\Projects\C++\Raylib\BulletFun\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BulletFun

# Build rule for target.
BulletFun: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 BulletFun
.PHONY : BulletFun

# fast build rule for target.
BulletFun/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/build
.PHONY : BulletFun/fast

src/abilityManager.o: src/abilityManager.cpp.o
.PHONY : src/abilityManager.o

# target to build an object file
src/abilityManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/abilityManager.cpp.o
.PHONY : src/abilityManager.cpp.o

src/abilityManager.i: src/abilityManager.cpp.i
.PHONY : src/abilityManager.i

# target to preprocess a source file
src/abilityManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/abilityManager.cpp.i
.PHONY : src/abilityManager.cpp.i

src/abilityManager.s: src/abilityManager.cpp.s
.PHONY : src/abilityManager.s

# target to generate assembly for a file
src/abilityManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/abilityManager.cpp.s
.PHONY : src/abilityManager.cpp.s

src/archer.o: src/archer.cpp.o
.PHONY : src/archer.o

# target to build an object file
src/archer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/archer.cpp.o
.PHONY : src/archer.cpp.o

src/archer.i: src/archer.cpp.i
.PHONY : src/archer.i

# target to preprocess a source file
src/archer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/archer.cpp.i
.PHONY : src/archer.cpp.i

src/archer.s: src/archer.cpp.s
.PHONY : src/archer.s

# target to generate assembly for a file
src/archer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/archer.cpp.s
.PHONY : src/archer.cpp.s

src/auraDmg.o: src/auraDmg.cpp.o
.PHONY : src/auraDmg.o

# target to build an object file
src/auraDmg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/auraDmg.cpp.o
.PHONY : src/auraDmg.cpp.o

src/auraDmg.i: src/auraDmg.cpp.i
.PHONY : src/auraDmg.i

# target to preprocess a source file
src/auraDmg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/auraDmg.cpp.i
.PHONY : src/auraDmg.cpp.i

src/auraDmg.s: src/auraDmg.cpp.s
.PHONY : src/auraDmg.s

# target to generate assembly for a file
src/auraDmg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/auraDmg.cpp.s
.PHONY : src/auraDmg.cpp.s

src/background.o: src/background.cpp.o
.PHONY : src/background.o

# target to build an object file
src/background.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/background.cpp.o
.PHONY : src/background.cpp.o

src/background.i: src/background.cpp.i
.PHONY : src/background.i

# target to preprocess a source file
src/background.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/background.cpp.i
.PHONY : src/background.cpp.i

src/background.s: src/background.cpp.s
.PHONY : src/background.s

# target to generate assembly for a file
src/background.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/background.cpp.s
.PHONY : src/background.cpp.s

src/blizzard.o: src/blizzard.cpp.o
.PHONY : src/blizzard.o

# target to build an object file
src/blizzard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/blizzard.cpp.o
.PHONY : src/blizzard.cpp.o

src/blizzard.i: src/blizzard.cpp.i
.PHONY : src/blizzard.i

# target to preprocess a source file
src/blizzard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/blizzard.cpp.i
.PHONY : src/blizzard.cpp.i

src/blizzard.s: src/blizzard.cpp.s
.PHONY : src/blizzard.s

# target to generate assembly for a file
src/blizzard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/blizzard.cpp.s
.PHONY : src/blizzard.cpp.s

src/bullet.o: src/bullet.cpp.o
.PHONY : src/bullet.o

# target to build an object file
src/bullet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/bullet.cpp.o
.PHONY : src/bullet.cpp.o

src/bullet.i: src/bullet.cpp.i
.PHONY : src/bullet.i

# target to preprocess a source file
src/bullet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/bullet.cpp.i
.PHONY : src/bullet.cpp.i

src/bullet.s: src/bullet.cpp.s
.PHONY : src/bullet.s

# target to generate assembly for a file
src/bullet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/bullet.cpp.s
.PHONY : src/bullet.cpp.s

src/characterSelection.o: src/characterSelection.cpp.o
.PHONY : src/characterSelection.o

# target to build an object file
src/characterSelection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/characterSelection.cpp.o
.PHONY : src/characterSelection.cpp.o

src/characterSelection.i: src/characterSelection.cpp.i
.PHONY : src/characterSelection.i

# target to preprocess a source file
src/characterSelection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/characterSelection.cpp.i
.PHONY : src/characterSelection.cpp.i

src/characterSelection.s: src/characterSelection.cpp.s
.PHONY : src/characterSelection.s

# target to generate assembly for a file
src/characterSelection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/characterSelection.cpp.s
.PHONY : src/characterSelection.cpp.s

src/enemy.o: src/enemy.cpp.o
.PHONY : src/enemy.o

# target to build an object file
src/enemy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemy.cpp.o
.PHONY : src/enemy.cpp.o

src/enemy.i: src/enemy.cpp.i
.PHONY : src/enemy.i

# target to preprocess a source file
src/enemy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemy.cpp.i
.PHONY : src/enemy.cpp.i

src/enemy.s: src/enemy.cpp.s
.PHONY : src/enemy.s

# target to generate assembly for a file
src/enemy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemy.cpp.s
.PHONY : src/enemy.cpp.s

src/enemySpawner.o: src/enemySpawner.cpp.o
.PHONY : src/enemySpawner.o

# target to build an object file
src/enemySpawner.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemySpawner.cpp.o
.PHONY : src/enemySpawner.cpp.o

src/enemySpawner.i: src/enemySpawner.cpp.i
.PHONY : src/enemySpawner.i

# target to preprocess a source file
src/enemySpawner.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemySpawner.cpp.i
.PHONY : src/enemySpawner.cpp.i

src/enemySpawner.s: src/enemySpawner.cpp.s
.PHONY : src/enemySpawner.s

# target to generate assembly for a file
src/enemySpawner.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/enemySpawner.cpp.s
.PHONY : src/enemySpawner.cpp.s

src/fireBreath.o: src/fireBreath.cpp.o
.PHONY : src/fireBreath.o

# target to build an object file
src/fireBreath.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/fireBreath.cpp.o
.PHONY : src/fireBreath.cpp.o

src/fireBreath.i: src/fireBreath.cpp.i
.PHONY : src/fireBreath.i

# target to preprocess a source file
src/fireBreath.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/fireBreath.cpp.i
.PHONY : src/fireBreath.cpp.i

src/fireBreath.s: src/fireBreath.cpp.s
.PHONY : src/fireBreath.s

# target to generate assembly for a file
src/fireBreath.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/fireBreath.cpp.s
.PHONY : src/fireBreath.cpp.s

src/grunt.o: src/grunt.cpp.o
.PHONY : src/grunt.o

# target to build an object file
src/grunt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/grunt.cpp.o
.PHONY : src/grunt.cpp.o

src/grunt.i: src/grunt.cpp.i
.PHONY : src/grunt.i

# target to preprocess a source file
src/grunt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/grunt.cpp.i
.PHONY : src/grunt.cpp.i

src/grunt.s: src/grunt.cpp.s
.PHONY : src/grunt.s

# target to generate assembly for a file
src/grunt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/grunt.cpp.s
.PHONY : src/grunt.cpp.s

src/imgui.o: src/imgui.cpp.o
.PHONY : src/imgui.o

# target to build an object file
src/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui.cpp.o
.PHONY : src/imgui.cpp.o

src/imgui.i: src/imgui.cpp.i
.PHONY : src/imgui.i

# target to preprocess a source file
src/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui.cpp.i
.PHONY : src/imgui.cpp.i

src/imgui.s: src/imgui.cpp.s
.PHONY : src/imgui.s

# target to generate assembly for a file
src/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui.cpp.s
.PHONY : src/imgui.cpp.s

src/imgui_demo.o: src/imgui_demo.cpp.o
.PHONY : src/imgui_demo.o

# target to build an object file
src/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_demo.cpp.o
.PHONY : src/imgui_demo.cpp.o

src/imgui_demo.i: src/imgui_demo.cpp.i
.PHONY : src/imgui_demo.i

# target to preprocess a source file
src/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_demo.cpp.i
.PHONY : src/imgui_demo.cpp.i

src/imgui_demo.s: src/imgui_demo.cpp.s
.PHONY : src/imgui_demo.s

# target to generate assembly for a file
src/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_demo.cpp.s
.PHONY : src/imgui_demo.cpp.s

src/imgui_draw.o: src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.o

# target to build an object file
src/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_draw.cpp.o
.PHONY : src/imgui_draw.cpp.o

src/imgui_draw.i: src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.i

# target to preprocess a source file
src/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_draw.cpp.i
.PHONY : src/imgui_draw.cpp.i

src/imgui_draw.s: src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.s

# target to generate assembly for a file
src/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_draw.cpp.s
.PHONY : src/imgui_draw.cpp.s

src/imgui_tables.o: src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.o

# target to build an object file
src/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_tables.cpp.o
.PHONY : src/imgui_tables.cpp.o

src/imgui_tables.i: src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.i

# target to preprocess a source file
src/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_tables.cpp.i
.PHONY : src/imgui_tables.cpp.i

src/imgui_tables.s: src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.s

# target to generate assembly for a file
src/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_tables.cpp.s
.PHONY : src/imgui_tables.cpp.s

src/imgui_widgets.o: src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.o

# target to build an object file
src/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_widgets.cpp.o
.PHONY : src/imgui_widgets.cpp.o

src/imgui_widgets.i: src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.i

# target to preprocess a source file
src/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_widgets.cpp.i
.PHONY : src/imgui_widgets.cpp.i

src/imgui_widgets.s: src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.s

# target to generate assembly for a file
src/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/imgui_widgets.cpp.s
.PHONY : src/imgui_widgets.cpp.s

src/inGameMenu.o: src/inGameMenu.cpp.o
.PHONY : src/inGameMenu.o

# target to build an object file
src/inGameMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/inGameMenu.cpp.o
.PHONY : src/inGameMenu.cpp.o

src/inGameMenu.i: src/inGameMenu.cpp.i
.PHONY : src/inGameMenu.i

# target to preprocess a source file
src/inGameMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/inGameMenu.cpp.i
.PHONY : src/inGameMenu.cpp.i

src/inGameMenu.s: src/inGameMenu.cpp.s
.PHONY : src/inGameMenu.s

# target to generate assembly for a file
src/inGameMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/inGameMenu.cpp.s
.PHONY : src/inGameMenu.cpp.s

src/levelUp.o: src/levelUp.cpp.o
.PHONY : src/levelUp.o

# target to build an object file
src/levelUp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/levelUp.cpp.o
.PHONY : src/levelUp.cpp.o

src/levelUp.i: src/levelUp.cpp.i
.PHONY : src/levelUp.i

# target to preprocess a source file
src/levelUp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/levelUp.cpp.i
.PHONY : src/levelUp.cpp.i

src/levelUp.s: src/levelUp.cpp.s
.PHONY : src/levelUp.s

# target to generate assembly for a file
src/levelUp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/levelUp.cpp.s
.PHONY : src/levelUp.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/player.o: src/player.cpp.o
.PHONY : src/player.o

# target to build an object file
src/player.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/player.cpp.o
.PHONY : src/player.cpp.o

src/player.i: src/player.cpp.i
.PHONY : src/player.i

# target to preprocess a source file
src/player.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/player.cpp.i
.PHONY : src/player.cpp.i

src/player.s: src/player.cpp.s
.PHONY : src/player.s

# target to generate assembly for a file
src/player.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/player.cpp.s
.PHONY : src/player.cpp.s

src/powerup.o: src/powerup.cpp.o
.PHONY : src/powerup.o

# target to build an object file
src/powerup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/powerup.cpp.o
.PHONY : src/powerup.cpp.o

src/powerup.i: src/powerup.cpp.i
.PHONY : src/powerup.i

# target to preprocess a source file
src/powerup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/powerup.cpp.i
.PHONY : src/powerup.cpp.i

src/powerup.s: src/powerup.cpp.s
.PHONY : src/powerup.s

# target to generate assembly for a file
src/powerup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/powerup.cpp.s
.PHONY : src/powerup.cpp.s

src/rlImGui.o: src/rlImGui.cpp.o
.PHONY : src/rlImGui.o

# target to build an object file
src/rlImGui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rlImGui.cpp.o
.PHONY : src/rlImGui.cpp.o

src/rlImGui.i: src/rlImGui.cpp.i
.PHONY : src/rlImGui.i

# target to preprocess a source file
src/rlImGui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rlImGui.cpp.i
.PHONY : src/rlImGui.cpp.i

src/rlImGui.s: src/rlImGui.cpp.s
.PHONY : src/rlImGui.s

# target to generate assembly for a file
src/rlImGui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rlImGui.cpp.s
.PHONY : src/rlImGui.cpp.s

src/rotatingBalls.o: src/rotatingBalls.cpp.o
.PHONY : src/rotatingBalls.o

# target to build an object file
src/rotatingBalls.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rotatingBalls.cpp.o
.PHONY : src/rotatingBalls.cpp.o

src/rotatingBalls.i: src/rotatingBalls.cpp.i
.PHONY : src/rotatingBalls.i

# target to preprocess a source file
src/rotatingBalls.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rotatingBalls.cpp.i
.PHONY : src/rotatingBalls.cpp.i

src/rotatingBalls.s: src/rotatingBalls.cpp.s
.PHONY : src/rotatingBalls.s

# target to generate assembly for a file
src/rotatingBalls.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/rotatingBalls.cpp.s
.PHONY : src/rotatingBalls.cpp.s

src/skillBar.o: src/skillBar.cpp.o
.PHONY : src/skillBar.o

# target to build an object file
src/skillBar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillBar.cpp.o
.PHONY : src/skillBar.cpp.o

src/skillBar.i: src/skillBar.cpp.i
.PHONY : src/skillBar.i

# target to preprocess a source file
src/skillBar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillBar.cpp.i
.PHONY : src/skillBar.cpp.i

src/skillBar.s: src/skillBar.cpp.s
.PHONY : src/skillBar.s

# target to generate assembly for a file
src/skillBar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillBar.cpp.s
.PHONY : src/skillBar.cpp.s

src/skillPickup.o: src/skillPickup.cpp.o
.PHONY : src/skillPickup.o

# target to build an object file
src/skillPickup.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillPickup.cpp.o
.PHONY : src/skillPickup.cpp.o

src/skillPickup.i: src/skillPickup.cpp.i
.PHONY : src/skillPickup.i

# target to preprocess a source file
src/skillPickup.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillPickup.cpp.i
.PHONY : src/skillPickup.cpp.i

src/skillPickup.s: src/skillPickup.cpp.s
.PHONY : src/skillPickup.s

# target to generate assembly for a file
src/skillPickup.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/skillPickup.cpp.s
.PHONY : src/skillPickup.cpp.s

src/slash.o: src/slash.cpp.o
.PHONY : src/slash.o

# target to build an object file
src/slash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slash.cpp.o
.PHONY : src/slash.cpp.o

src/slash.i: src/slash.cpp.i
.PHONY : src/slash.i

# target to preprocess a source file
src/slash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slash.cpp.i
.PHONY : src/slash.cpp.i

src/slash.s: src/slash.cpp.s
.PHONY : src/slash.s

# target to generate assembly for a file
src/slash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slash.cpp.s
.PHONY : src/slash.cpp.s

src/slime.o: src/slime.cpp.o
.PHONY : src/slime.o

# target to build an object file
src/slime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slime.cpp.o
.PHONY : src/slime.cpp.o

src/slime.i: src/slime.cpp.i
.PHONY : src/slime.i

# target to preprocess a source file
src/slime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slime.cpp.i
.PHONY : src/slime.cpp.i

src/slime.s: src/slime.cpp.s
.PHONY : src/slime.s

# target to generate assembly for a file
src/slime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/slime.cpp.s
.PHONY : src/slime.cpp.s

src/terrainCollisionDetection.o: src/terrainCollisionDetection.cpp.o
.PHONY : src/terrainCollisionDetection.o

# target to build an object file
src/terrainCollisionDetection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/terrainCollisionDetection.cpp.o
.PHONY : src/terrainCollisionDetection.cpp.o

src/terrainCollisionDetection.i: src/terrainCollisionDetection.cpp.i
.PHONY : src/terrainCollisionDetection.i

# target to preprocess a source file
src/terrainCollisionDetection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/terrainCollisionDetection.cpp.i
.PHONY : src/terrainCollisionDetection.cpp.i

src/terrainCollisionDetection.s: src/terrainCollisionDetection.cpp.s
.PHONY : src/terrainCollisionDetection.s

# target to generate assembly for a file
src/terrainCollisionDetection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/terrainCollisionDetection.cpp.s
.PHONY : src/terrainCollisionDetection.cpp.s

src/tilemap.o: src/tilemap.cpp.o
.PHONY : src/tilemap.o

# target to build an object file
src/tilemap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/tilemap.cpp.o
.PHONY : src/tilemap.cpp.o

src/tilemap.i: src/tilemap.cpp.i
.PHONY : src/tilemap.i

# target to preprocess a source file
src/tilemap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/tilemap.cpp.i
.PHONY : src/tilemap.cpp.i

src/tilemap.s: src/tilemap.cpp.s
.PHONY : src/tilemap.s

# target to generate assembly for a file
src/tilemap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\BulletFun.dir\build.make CMakeFiles/BulletFun.dir/src/tilemap.cpp.s
.PHONY : src/tilemap.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... BulletFun
	@echo ... src/abilityManager.o
	@echo ... src/abilityManager.i
	@echo ... src/abilityManager.s
	@echo ... src/archer.o
	@echo ... src/archer.i
	@echo ... src/archer.s
	@echo ... src/auraDmg.o
	@echo ... src/auraDmg.i
	@echo ... src/auraDmg.s
	@echo ... src/background.o
	@echo ... src/background.i
	@echo ... src/background.s
	@echo ... src/blizzard.o
	@echo ... src/blizzard.i
	@echo ... src/blizzard.s
	@echo ... src/bullet.o
	@echo ... src/bullet.i
	@echo ... src/bullet.s
	@echo ... src/characterSelection.o
	@echo ... src/characterSelection.i
	@echo ... src/characterSelection.s
	@echo ... src/enemy.o
	@echo ... src/enemy.i
	@echo ... src/enemy.s
	@echo ... src/enemySpawner.o
	@echo ... src/enemySpawner.i
	@echo ... src/enemySpawner.s
	@echo ... src/fireBreath.o
	@echo ... src/fireBreath.i
	@echo ... src/fireBreath.s
	@echo ... src/grunt.o
	@echo ... src/grunt.i
	@echo ... src/grunt.s
	@echo ... src/imgui.o
	@echo ... src/imgui.i
	@echo ... src/imgui.s
	@echo ... src/imgui_demo.o
	@echo ... src/imgui_demo.i
	@echo ... src/imgui_demo.s
	@echo ... src/imgui_draw.o
	@echo ... src/imgui_draw.i
	@echo ... src/imgui_draw.s
	@echo ... src/imgui_tables.o
	@echo ... src/imgui_tables.i
	@echo ... src/imgui_tables.s
	@echo ... src/imgui_widgets.o
	@echo ... src/imgui_widgets.i
	@echo ... src/imgui_widgets.s
	@echo ... src/inGameMenu.o
	@echo ... src/inGameMenu.i
	@echo ... src/inGameMenu.s
	@echo ... src/levelUp.o
	@echo ... src/levelUp.i
	@echo ... src/levelUp.s
	@echo ... src/main.o
	@echo ... src/main.i
	@echo ... src/main.s
	@echo ... src/player.o
	@echo ... src/player.i
	@echo ... src/player.s
	@echo ... src/powerup.o
	@echo ... src/powerup.i
	@echo ... src/powerup.s
	@echo ... src/rlImGui.o
	@echo ... src/rlImGui.i
	@echo ... src/rlImGui.s
	@echo ... src/rotatingBalls.o
	@echo ... src/rotatingBalls.i
	@echo ... src/rotatingBalls.s
	@echo ... src/skillBar.o
	@echo ... src/skillBar.i
	@echo ... src/skillBar.s
	@echo ... src/skillPickup.o
	@echo ... src/skillPickup.i
	@echo ... src/skillPickup.s
	@echo ... src/slash.o
	@echo ... src/slash.i
	@echo ... src/slash.s
	@echo ... src/slime.o
	@echo ... src/slime.i
	@echo ... src/slime.s
	@echo ... src/terrainCollisionDetection.o
	@echo ... src/terrainCollisionDetection.i
	@echo ... src/terrainCollisionDetection.s
	@echo ... src/tilemap.o
	@echo ... src/tilemap.i
	@echo ... src/tilemap.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

